# Copyright 2016 Apcera Inc. All rights reserved.
cache:
  directories:
  - $HOME/gnatsd
before_install:
  - bash ./scripts/install_gnatsd.sh
before_script:
  - export PATH=$HOME/gnatsd:$PATH
language: elixir
otp_release:
  - 18.0
elixir:
  - 1.2.2
sudo: false
script:
  - ./test/run-test-servers.sh < /dev/null 2>&1 &
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
